"""Agent-X Strategy and Planning Engine Schemas and Data Models."""

from datetime import UTC, datetime
from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from agentx.goal_engine.schemas import RiskLevel
from agentx.kernel.models import Goal, SuccessCriteria, Task
from agentx.unknowns.schemas import EpistemicUnknown
from agentx.world_model.models import Constraint, Risk, WorldModelEntity
from agentx_common.schemas import AgentRole, MissionBudget, VerificationLevel


class StrategyType(StrEnum):
    """Archetype style for candidate execution strategies."""

    FAST_DIRECT = "FAST_DIRECT"  # Minimal exploration, parallel fast execution
    BALANCED = "BALANCED"  # Standard staged execution with testing
    CONSERVATIVE_HARDENED = (
        "CONSERVATIVE_HARDENED"  # Extensive upfront discovery & formal verification
    )


class PlanningContext(BaseModel):
    """Complete aggregated contextual state provided to the Planning Engine."""

    model_config = ConfigDict(extra="forbid")

    mission_id: str
    goal: Goal
    success_criteria: list[SuccessCriteria] = Field(default_factory=list)
    entities: list[WorldModelEntity] = Field(default_factory=list)
    unknowns: list[EpistemicUnknown] = Field(default_factory=list)
    constraints: list[Constraint] = Field(default_factory=list)
    risks: list[Risk] = Field(default_factory=list)
    budget: MissionBudget = Field(default_factory=MissionBudget)
    deadline_seconds: int = Field(default=3600, gt=0)
    available_agents: list[AgentRole] = Field(
        default_factory=lambda: [
            AgentRole.COORDINATOR,
            AgentRole.ARCHITECT,
            AgentRole.CODER,
            AgentRole.TESTER,
            AgentRole.DEVOPS,
            AgentRole.AUDITOR,
        ]
    )
    available_tools: list[str] = Field(
        default_factory=lambda: [
            "run_command",
            "read_file",
            "write_file",
            "grep_search",
            "gcloud_cli",
            "terraform_cli",
            "pytest_runner",
        ]
    )


class TaskDraftDTO(BaseModel):
    """DTO for LLM structured strategy task output."""

    task_id: str
    name: str
    description: str
    agent_role: AgentRole
    dependencies: list[str] = Field(default_factory=list)
    expected_outputs: list[str] = Field(default_factory=list)
    allocated_tokens: int = 25000
    timeout_seconds: int = 300
    verification_level: VerificationLevel = VerificationLevel.LEVEL_3_ARTIFACT


class StrategyDraftDTO(BaseModel):
    """Structured representation of a candidate strategy generated by LLM reasoning."""

    strategy_id: str
    strategy_type: StrategyType
    name: str
    description: str
    tasks: list[TaskDraftDTO]
    estimated_cost_usd: float
    estimated_tokens: int
    estimated_duration_seconds: int
    risk: RiskLevel
    risk_score: float = Field(..., ge=0.0, le=1.0)
    expected_success_probability: float = Field(..., ge=0.0, le=1.0)
    required_capabilities: list[AgentRole]
    tradeoffs: list[str] = Field(default_factory=list)


class CandidateStrategy(BaseModel):
    """A fully validated, executable candidate strategy with instantiated Task DAG nodes."""

    model_config = ConfigDict(extra="forbid")

    strategy_id: str = Field(default_factory=lambda: f"strat_{uuid4().hex[:8]}")
    strategy_type: StrategyType
    name: str
    description: str
    tasks: list[Task]
    dependencies: dict[str, list[str]] = Field(
        default_factory=dict, description="Adjacency list mapping task_id to its prerequisites"
    )
    estimated_cost_usd: float = Field(..., ge=0.0)
    estimated_tokens: int = Field(..., ge=0)
    estimated_duration_seconds: int = Field(..., ge=0)
    risk: RiskLevel
    risk_score: float = Field(..., ge=0.0, le=1.0)
    expected_success_probability: float = Field(..., ge=0.0, le=1.0)
    required_capabilities: list[AgentRole]
    tradeoffs: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class StrategySelectionCriteria(BaseModel):
    """User and system preferences governing strategy selection."""

    model_config = ConfigDict(extra="forbid")

    max_usd_budget: float | None = None
    max_duration_seconds: int | None = None
    weight_success_probability: float = Field(default=0.45, ge=0.0, le=1.0)
    weight_risk_penalty: float = Field(default=0.25, ge=0.0, le=1.0)
    weight_cost_efficiency: float = Field(default=0.15, ge=0.0, le=1.0)
    weight_speed_efficiency: float = Field(default=0.15, ge=0.0, le=1.0)


class ScoredStrategy(BaseModel):
    """A candidate strategy evaluated against selection criteria."""

    model_config = ConfigDict(extra="forbid")

    strategy: CandidateStrategy
    utility_score: float
    is_feasible: bool
    rejection_reasons: list[str] = Field(default_factory=list)


class StrategySelectionResult(BaseModel):
    """The final strategy decision outcome with transparent ranking and justification."""

    model_config = ConfigDict(extra="forbid")

    selected_strategy: CandidateStrategy
    selection_rationale: str
    candidates_ranked: list[ScoredStrategy]
    selection_timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
